export const ADD_QUES = 'ADD_QUES'
export const GET_QUES_AND_COMMENTS = 'GET_QUES_AND_COMMENTS'
export const ADD_COMMENT = 'ADD_COMMENT'
export const GET_QUESTIONSLIST = 'GET_QUESTIONSLIST'
export const GET_COMMENTSLIST = 'GET_COMMENTSLIST'

export const LOAD_MORE_ANSWER = 'LOAD_MORE_ANSWER'
export const COMMENT_COUNT = 'COMMENT_COUNT'
export const LOAD_MORE_QUESTION = 'LOAD_MORE_QUESTION'

// 格式化time
export const FORMAT_TIME = 'FORMAT_TIME'
